// GENERATED STATIC_PRIZES
const STATIC_PRIZES = [
  {
    id: 'premio-boxer-chess-king',
    name: 'Boxer Chess King',
    description: 'Producto oficial Chess King.',
    points_cost: 100,
    units_available: 1,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1779802466542_rbr78y.png',
    gradient: 'from-emerald-600 to-emerald-800',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-',
    name: '',
    description: 'Producto oficial Chess King.',
    points_cost: 100,
    units_available: 1,
    status: 'active',
    image_url: '',
    gradient: 'from-amber-500 to-orange-700',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-gorra-chess-king-by-anyuri',
    name: 'Gorra Chess King By Anyuri',
    description: 'Producto oficial Chess King.',
    points_cost: 500,
    units_available: 1,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1779802521578_wppte9.png',
    gradient: 'from-violet-600 to-purple-900',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-gorra-chess-king',
    name: 'Gorra Chess King',
    description: 'Color gris unicamente',
    points_cost: 500,
    units_available: 6,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1779802566894_88qdy5.png',
    gradient: 'from-pink-500 to-rose-800',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-jogger-chess-king',
    name: 'Jogger - Chess King',
    description: 'Talla L',
    points_cost: 200,
    units_available: 2,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1779802775853_19dmr7.png',
    gradient: 'from-cyan-500 to-blue-800',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-pantalon-playero-chess-king',
    name: 'Pantalon Playero - Chess King',
    description: 'Producto oficial Chess King.',
    points_cost: 100,
    units_available: 2,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1779802817887_nv9q0n.png',
    gradient: 'from-blue-600 to-indigo-800',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-pantalon-playero-chees-king',
    name: 'Pantalon Playero Chees king',
    description: 'Colores surtidos (Negro, mostaza, rojo, blanco, azul)',
    points_cost: 100,
    units_available: 1,
    status: 'active',
    image_url: '',
    gradient: 'from-rose-500 to-red-800',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-tshirts-anyuri-by-chess-king',
    name: 'Tshirts Anyuri By Chess King',
    description: 'Colores Azul y rosa',
    points_cost: 100,
    units_available: 1,
    status: 'active',
    image_url: '',
    gradient: 'from-teal-500 to-green-800',
    icon: '🎁',
    sizes: {"S":1},
  },
  {
    id: 'premio-tshirts-chess-king',
    name: 'Tshirts Chess King',
    description: 'Talla M',
    points_cost: 500,
    units_available: 6,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1780007099712_wzhbqv.png',
    gradient: 'from-orange-500 to-red-700',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-tshirts-manga-larga-chess-king',
    name: 'Tshirts - Manga Larga Chess King',
    description: 'Producto oficial Chess King.',
    points_cost: 100,
    units_available: 1,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1780007202843_kadkk6.png',
    gradient: 'from-sky-500 to-blue-800',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-hoodie-chess-king',
    name: 'Hoodie Chess King',
    description: 'Producto oficial Chess King.',
    points_cost: 100,
    units_available: 1,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1780007225709_elrfoq.png',
    gradient: 'from-lime-500 to-green-700',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-tshirts-munga-larga-chess-king',
    name: 'Tshirts - Munga Larga Chess King',
    description: 'Tallas M Blanco (2) negro (1)',
    points_cost: 600,
    units_available: 3,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1780954897549_84x7rz.png',
    gradient: 'from-fuchsia-500 to-purple-800',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-tshirts-manga-corta-chess-king',
    name: 'Tshirts - Manga Corta Chess King',
    description: 'Producto oficial Chess King.',
    points_cost: 100,
    units_available: 3,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1780007316206_e5ar70.png',
    gradient: 'from-emerald-600 to-emerald-800',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-box-anyuri-by-chess-king-edicion-limitada',
    name: 'Box - Anyuri By Chess King - Edicion Limitada',
    description: 'Kit sin muñeca, solo T-shirt y gorra.',
    points_cost: 800,
    units_available: 3,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1780007362998_x60t69.png',
    gradient: 'from-amber-500 to-orange-700',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-tshirt-manga-corta-chees-king',
    name: 'Tshirt-Manga Corta Chees King',
    description: 'Producto oficial Chess King.',
    points_cost: 400,
    units_available: 1,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1780954921993_8ut8p8.png',
    gradient: 'from-violet-600 to-purple-900',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-t-shirt-chees-king',
    name: 'T-shirt Chees King',
    description: 'Unicos modelos, los print varian',
    points_cost: 100,
    units_available: 1,
    status: 'active',
    image_url: '',
    gradient: 'from-pink-500 to-rose-800',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-tshirt-chees-king',
    name: 'Tshirt Chees King',
    description: 'Talla m',
    points_cost: 500,
    units_available: 3,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1780955106572_abk7cg.png',
    gradient: 'from-cyan-500 to-blue-800',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-pantalones-hype-chees-king',
    name: 'Pantalones hype - Chees King',
    description: 'Talla 36 (2 unidades)',
    points_cost: 100,
    units_available: 1,
    status: 'active',
    image_url: '',
    gradient: 'from-blue-600 to-indigo-800',
    icon: '🎁',
    sizes: {"36":2},
  },
  {
    id: 'premio-pantalon-bermuda-chees-king',
    name: 'Pantalon Bermuda - Chees king',
    description: 'Talla 32',
    points_cost: 600,
    units_available: 2,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1780955706928_po0knd.png',
    gradient: 'from-rose-500 to-red-800',
    icon: '🎁',
    sizes: {"3":8},
  },
  {
    id: 'premio-gorros-bucket-chees-king',
    name: 'Gorros bucket Chees King',
    description: 'Producto oficial Chess King.',
    points_cost: 500,
    units_available: 34,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1780955840852_wlhy7c.png',
    gradient: 'from-teal-500 to-green-800',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-tshirt-bascias-chees-king',
    name: 'Tshirt Bascias Chees King',
    description: 'Talla S (Unidades 2)',
    points_cost: 100,
    units_available: 1,
    status: 'active',
    image_url: '',
    gradient: 'from-orange-500 to-red-700',
    icon: '🎁',
    sizes: null,
  },
  {
    id: 'premio-tshirt-basicas-talla-s-chees-king',
    name: 'Tshirt Basicas Talla S Chees King',
    description: 'Talla S.',
    points_cost: 500,
    units_available: 6,
    status: 'active',
    image_url: 'https://khrxddafhzvfdyivysay.supabase.co/storage/v1/object/public/banners/1780957859123_thwqbm.png',
    gradient: 'from-sky-500 to-blue-800',
    icon: '🎁',
    sizes: null,
  },
];

// Total: 22 premios únicos
